[colors]
foreground = "#A0A0AF"
background = "#171719"
cursor_bg = "#A0A0AF"
cursor_border = "#61616A"
cursor_fg = "#171719"
selection_bg = "#2A2A2B"
selection_fg = "#B9B8E3"
split = "#61616A"
compose_cursor = "#ABBDEE"
scrollbar_thumb = "#1F1F21"

ansi = ["#1F1F21", "#A67E97", "#738980", "#A68170", "#6C81B8", "#6E6DA7", "#55787D", "#606069"]
brights = ["#61616A", "#cf9dbd", "#90aba0", "#cfa18c", "#87a1e6", "#8a88d1", "#6a969c", "#A0A0AF"]

[colors.tab_bar]
inactive_tab_edge = "#606069"
background = "#171719"

[colors.tab_bar.active_tab]
fg_color = "#ABBDEE"
bg_color = "#2A2A2B"

[colors.tab_bar.inactive_tab]
fg_color = "#61616A"
bg_color = "#1F1F21"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#61616A"
bg_color = "#1F1F21"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#ABBDEE"
bg_color = "#2A2A2B"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#ABBDEE"
bg_color = "#171719"

[metadata]
aliases = []
name = "iceclimber"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/"
author = "Casey Miller"
