[colors]
foreground = "#C4B6C5"
background = "#141517"
cursor_bg = "#C4B6C5"
cursor_border = "#666068"
cursor_fg = "#141517"
selection_bg = "#27282A"
selection_fg = "#9bbdb8"
split = "#666068"
compose_cursor = "#9FB6D0"
scrollbar_thumb = "#1C1D1F"

ansi = ["#1C1D1F", "#9D777D", "#7C9793", "#A18877", "#788CC2", "#8583BC", "#4C6B8D", "#766D76"]
brights = ["#666068", "#c4959c", "#9bbdb8", "#c9aa95", "#96aff2", "#a6a4eb", "#5f86b0", "#C4B6C5"]

[colors.tab_bar]
inactive_tab_edge = "#766D76"
background = "#141517"

[colors.tab_bar.active_tab]
fg_color = "#9FB6D0"
bg_color = "#27282A"

[colors.tab_bar.inactive_tab]
fg_color = "#666068"
bg_color = "#1C1D1F"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#666068"
bg_color = "#1C1D1F"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#9FB6D0"
bg_color = "#27282A"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#9FB6D0"
bg_color = "#141517"

[metadata]
aliases = []
name = "roseprime"
url = "https://wezfurlong.org/wezterm/config/files.html"
upstream = "https://github.com/cdmill/neomodern.nvim/raw/main/extras/"
author = "Casey Miller"
