# name: gyokuro colors for alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

# Default colors
[colors.primary]
background = '#1b1c1d'
foreground = '#AFB0A6'

#[colors.cursor]
#cursor = '#AFB0A6'
#text = '#1b1c1d'

# Normal colors
[colors.normal]
black = '#232425'
red = '#AB878F'
green = '#61765E'
yellow = '#857E59'
blue = '#5D7285'
magenta = '#6B7191'
cyan = '#8D7064'
white = '#696A64'

# Bright colors
[colors.bright]
black = '#6B6B67'
red = '#d6a9b3'
green = '#799475'
yellow = '#a69e6f'
blue = '#748fa6'
magenta = '#868db5'
cyan = '#b08c7d'
white = '#AFB0A6'
