# name: hojicha colors for alacritty
# url: https://github.com/alacritty/alacritty
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

# Default colors
[colors.primary]
background = '#171614'
foreground = '#AEA09F'

#[colors.cursor]
#cursor = '#AEA09F'
#text = '#171614'

# Normal colors
[colors.normal]
black = '#1F1E1C'
red = '#6E665E'
green = '#5A6458'
yellow = '#8D8468'
blue = '#666C78'
magenta = '#6E6C7D'
cyan = '#896956'
white = '#68605F'

# Bright colors
[colors.bright]
black = '#68605F'
red = '#8a7f76'
green = '#717d6e'
yellow = '#b0a582'
blue = '#808796'
magenta = '#8a879c'
cyan = '#ab836c'
white = '#AEA09F'
