# name: gyokuro colors for yazi
# url: https://github.com/sxyazi/yazi
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

[mgr]
cwd = { fg = "#61765E" }

find_keyword  = { fg = "#748fa6", italic = true }
find_position = { fg = "#748fa6", bg = "reset", italic = true }

marker_copied   = { fg = "#d6a9b3", bg = "#d6a9b3" }
marker_cut      = { fg = "#E3878A", bg = "#E3878A", crossed = true }
marker_marked   = { bg = "#94A991", blink = true }
marker_selected = { bg = "#94A991", blink = true }

tab_active   = { fg = "#868db5", bg = "#232425", bold = true, reversed = true }
tab_inactive = { fg = "#6B6B67", bg = "#232425" }
tab_width    = 1

count_cut      = { fg = "#E3878A" }
count_copied   = { fg = "#d6a9b3" }
count_selected = { fg = "#94A991", italic = true, blink = true }

border_symbol = "│"
border_style  = { fg = "#6B6B67" }

[indicator]
current     = { fg = "#94A991", bg = "#232425" }
parent      = { fg = "#AFBFAC", bg = "#232425" }
preview     = { fg = "#AFBFAC", bg = "#232425" }

[mode]
normal_main   = { fg = "#1b1c1d", bg = "#799475" }
normal_alt    = { fg = "#1b1c1d", bg = "#799475" }
select_main   = { fg = "#1b1c1d", bg = "#94A991" }
select_alt    = { fg = "#1b1c1d", bg = "#94A991" }
unset_main    = { fg = "#1b1c1d", bg = "#748fa6" }
unset_alt     = { fg = "#1b1c1d", bg = "#748fa6" }

[status]
overall = {  fg = "#6B6B67", bg = "#1b1c1d", bold = true }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#868db5", bg = "#2D2E2F" }
progress_normal = { fg = "#868db5", bg = "#2D2E2F" }
progress_error  = { fg = "#E3878A", bg = "#2D2E2F" }

permissions_t = { fg = "#AFBFAC" }
permissions_r = { fg = "#748fa6" }
permissions_w = { fg = "#799475" }
permissions_x = { fg = "#61765E" }
permissions_s = { fg = "#868db5" }

[input]
border   = { fg = "#6B6B67" }
title    = { fg = "#868db5" }
value    = {}
selected = { fg = "#AFB0A6", bg = "#2D2E2F" }

[confirm]
border   = { fg = "#6B6B67" }
title = { fg = "#868db5" }
btn_yes = { fg = "#E3878A", bg = "#232425" }
btn_no = { fg = "#698E6F", bg = "#232425" }

[tasks]
border  = { fg = "#6B6B67" }
title    = { fg = "#868db5" }
hovered = { underline = true }

[which]
mask            = { bg = "#232425" }
cand            = { fg = "#d6a9b3" }
rest            = { fg = "#AFBFAC" }
desc            = { fg = "#748fa6" }
separator       = "  "
separator_style = { fg = "#b08c7d"}

[spot]
border = { fg = "#6B6B67" }
title = { fg = "#868db5" }
tbl_col = { fg = "#748fa6" }
tbl_cell = { fg = "#AFBFAC", bg = "#232425" }

[help]
on      = { fg = "#d6a9b3" }
run    = { fg = "#748fa6" }
desc    = { fg = "#6B6B67" }
hovered = { bg = "#232425", bold = true }
footer  = { fg = "#799475", bg = "#232425" }

[notify]
title_info = { fg = "#868db5" }
title_warn = { fg = "#AC9569" }
title_error = { fg = "#E3878A" }

[filetype]
rules = [
    # Media
    { mime = "image/*", fg = "#868db5"},
    { mime = "{audio,video}/*", fg = "#868db5"},

    # Archives
    { mime = "application/{,g}zip", fg = "#b08c7d"},
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#b08c7d"},

    # Fallback
    { url = "*", fg = "#AFB0A6"},
    { url = "*/", fg = "#5D7285"}
]
  