# name: roseprime colors for yazi
# url: https://github.com/sxyazi/yazi
# upstream: https://github.com/cdmill/neomodern.nvim/raw/main/extras/
# author: Casey Miller

[mgr]
cwd = { fg = "#c4959c" }

find_keyword  = { fg = "#9D777D", italic = true }
find_position = { fg = "#9D777D", bg = "reset", italic = true }

marker_copied   = { fg = "#A18877", bg = "#A18877" }
marker_cut      = { fg = "#DF8386", bg = "#DF8386", crossed = true }
marker_marked   = { bg = "#9FB6D0", blink = true }
marker_selected = { bg = "#9FB6D0", blink = true }

tab_active   = { fg = "#96aff2", bg = "#1C1D1F", bold = true, reversed = true }
tab_inactive = { fg = "#666068", bg = "#1C1D1F" }
tab_width    = 1

count_cut      = { fg = "#DF8386" }
count_copied   = { fg = "#A18877" }
count_selected = { fg = "#9FB6D0", italic = true, blink = true }

border_symbol = "│"
border_style  = { fg = "#666068" }

[indicator]
current     = { fg = "#9FB6D0", bg = "#1C1D1F" }
parent      = { fg = "#9bbdb8", bg = "#1C1D1F" }
preview     = { fg = "#9bbdb8", bg = "#1C1D1F" }

[mode]
normal_main   = { fg = "#141517", bg = "#5f86b0" }
normal_alt    = { fg = "#141517", bg = "#5f86b0" }
select_main   = { fg = "#141517", bg = "#9FB6D0" }
select_alt    = { fg = "#141517", bg = "#9FB6D0" }
unset_main    = { fg = "#141517", bg = "#9D777D" }
unset_alt     = { fg = "#141517", bg = "#9D777D" }

[status]
overall = {  fg = "#666068", bg = "#141517", bold = true }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#96aff2", bg = "#27282A" }
progress_normal = { fg = "#96aff2", bg = "#27282A" }
progress_error  = { fg = "#DF8386", bg = "#27282A" }

permissions_t = { fg = "#9bbdb8" }
permissions_r = { fg = "#9D777D" }
permissions_w = { fg = "#5f86b0" }
permissions_x = { fg = "#c4959c" }
permissions_s = { fg = "#96aff2" }

[input]
border   = { fg = "#666068" }
title    = { fg = "#96aff2" }
value    = {}
selected = { fg = "#C4B6C5", bg = "#27282A" }

[confirm]
border   = { fg = "#666068" }
title = { fg = "#96aff2" }
btn_yes = { fg = "#DF8386", bg = "#1C1D1F" }
btn_no = { fg = "#70967C", bg = "#1C1D1F" }

[tasks]
border  = { fg = "#666068" }
title    = { fg = "#96aff2" }
hovered = { underline = true }

[which]
mask            = { bg = "#1C1D1F" }
cand            = { fg = "#A18877" }
rest            = { fg = "#9bbdb8" }
desc            = { fg = "#9D777D" }
separator       = "  "
separator_style = { fg = "#9594D4"}

[spot]
border = { fg = "#666068" }
title = { fg = "#96aff2" }
tbl_col = { fg = "#9D777D" }
tbl_cell = { fg = "#9bbdb8", bg = "#1C1D1F" }

[help]
on      = { fg = "#A18877" }
run    = { fg = "#9D777D" }
desc    = { fg = "#666068" }
hovered = { bg = "#1C1D1F", bold = true }
footer  = { fg = "#5f86b0", bg = "#1C1D1F" }

[notify]
title_info = { fg = "#96aff2" }
title_warn = { fg = "#B39871" }
title_error = { fg = "#DF8386" }

[filetype]
rules = [
    # Media
    { mime = "image/*", fg = "#96aff2"},
    { mime = "{audio,video}/*", fg = "#96aff2"},

    # Archives
    { mime = "application/{,g}zip", fg = "#9594D4"},
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#9594D4"},

    # Fallback
    { url = "*", fg = "#C4B6C5"},
    { url = "*/", fg = "#788CC2"}
]
  